test:cargo:
  variables:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: full
  script:
  - rustup show
  - rustup default nightly-2026-03-03
  - cargo clean
  - cargo build --bin mech --release
  - ./target/release/mech test docs
  - ./target/release/mech test examples/working
  - cargo build --no-default-features
  - cargo test interpret
  - cargo test bytecode
  - cargo test -p mech-runtime --lib --tests