[package]
name = "bytecode-compiler-producer"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
mech-interpreter = {
  path = "../../../src/interpreter",
  default-features = false,
  features = ["program", "compiler", "functions", "symbol_table", "f64", "math_add"],
}
mech-engine = {
  path = "../../../src/engine",
  default-features = false,
  features = ["compiler", "functions", "formulas", "symbol_table", "f64"],
}

[patch.crates-io]
mech-bytecode = { path = "../../../src/bytecode" }
mech-core = { path = "../../../src/core" }
mech-syntax = { path = "../../../src/syntax" }
mech-interpreter = { path = "../../../src/interpreter" }
mech-engine = { path = "../../../src/engine" }
mech-combinatorics = { path = "../../../machines/combinatorics" }
mech-compare = { path = "../../../machines/compare" }
mech-logic = { path = "../../../machines/logic" }
mech-math = { path = "../../../machines/math" }
mech-matrix = { path = "../../../machines/matrix" }
mech-range = { path = "../../../machines/range" }
mech-set = { path = "../../../machines/set" }
mech-stats = { path = "../../../machines/stats" }
mech-string = { path = "../../../machines/string" }

[workspace]
