pub use crate::*;
#[cfg(feature = "abs")]
pub mod abs;
#[cfg(feature = "copysign")]
pub mod copysign;
#[cfg(feature = "fdim")]
pub mod fdim;
#[cfg(feature = "fmod")]
pub mod fmod;
#[cfg(feature = "nextafter")]
pub mod nextafter;
#[cfg(feature = "remainder")]
pub mod remainder;

#[cfg(feature = "abs")]
pub use self::abs::*;
#[cfg(feature = "copysign")]
pub use self::copysign::*;
#[cfg(feature = "fdim")]
pub use self::fdim::*;
#[cfg(feature = "fmod")]
pub use self::fmod::*;
#[cfg(feature = "nextafter")]
pub use self::nextafter::*;
#[cfg(feature = "remainder")]
pub use self::remainder::*;
