// Generated from docs/design/specification.mec and grammar-audit/ports.tsv.
// Do not edit by hand.

use crate::document::{RuleId, SyntaxKind};

use super::super::rule::rules;

#[derive(Clone, Copy, Debug)]
pub(crate) enum GrammarExpression {
    Rule(RuleId),
    Builtin(&'static str),
    Literal(&'static str),
    Empty,
    Sequence(&'static [GrammarExpression]),
    Choice(&'static [GrammarExpression]),
    BestChoice(&'static [GrammarExpression]),
    Optional(&'static GrammarExpression),
    ZeroOrMore(&'static GrammarExpression),
    OneOrMore(&'static GrammarExpression),
    Peek(&'static GrammarExpression),
    Not(&'static GrammarExpression),
    Separated {
        separator: &'static GrammarExpression,
        item: &'static GrammarExpression,
    },
}

pub(crate) struct DocumentRule {
    pub(crate) rule: RuleId,
    pub(crate) expression: GrammarExpression,
    pub(crate) kind: Option<SyntaxKind>,
    pub(crate) root: bool,
}

pub(crate) const DOCUMENT_RULE_COUNT: usize = 114;

pub(crate) static DOCUMENT_RULES: &[DocumentRule] = &[
    DocumentRule {
        rule: rules::ABSTRACT_EL,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::ABSTRACT_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::AbstractEl),
        root: false,
    },
    DocumentRule {
        rule: rules::ACTIVATION_ARM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::GUARD_OPERATOR),
            GrammarExpression::Rule(rules::PATTERN),
            GrammarExpression::Optional(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::LIST_SEPARATOR),
                GrammarExpression::Rule(rules::WHITESPACE0),
                GrammarExpression::Rule(rules::EXPRESSION),
            ])),
            GrammarExpression::Rule(rules::OUTPUT_OPERATOR),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Sequence(&[
                    GrammarExpression::Rule(rules::LEFT_BRACE),
                    GrammarExpression::Rule(rules::WHITESPACE0),
                    GrammarExpression::Optional(&GrammarExpression::Rule(rules::MECH_CODE)),
                    GrammarExpression::Rule(rules::RIGHT_BRACE),
                ]),
                GrammarExpression::Sequence(&[
                    GrammarExpression::Rule(rules::EXPRESSION),
                    GrammarExpression::Optional(&GrammarExpression::Choice(&[
                        GrammarExpression::Rule(rules::WHITESPACE1),
                        GrammarExpression::Rule(rules::STATEMENT_SEPARATOR),
                    ])),
                ]),
            ]),
        ]),
        kind: Some(SyntaxKind::ActivationArm),
        root: false,
    },
    DocumentRule {
        rule: rules::ACTIVATION_SCOPE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::ASYNC_TRANSITION_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Sequence(&[
                    GrammarExpression::Rule(rules::LEFT_BRACE),
                    GrammarExpression::Rule(rules::WHITESPACE0),
                    GrammarExpression::Optional(&GrammarExpression::Rule(rules::MECH_CODE)),
                    GrammarExpression::Rule(rules::RIGHT_BRACE),
                ]),
                GrammarExpression::Sequence(&[
                    GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::ACTIVATION_ARM)),
                    GrammarExpression::Optional(&GrammarExpression::Rule(rules::PERIOD)),
                ]),
            ]),
        ]),
        kind: Some(SyntaxKind::ActivationScope),
        root: false,
    },
    DocumentRule {
        rule: rules::ALIGNMENT_SEPARATOR,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::CENTER_ALIGNMENT),
                GrammarExpression::Rule(rules::LEFT_ALIGNMENT),
                GrammarExpression::Rule(rules::RIGHT_ALIGNMENT),
                GrammarExpression::Rule(rules::NO_ALIGNMENT),
            ]),
            GrammarExpression::Rule(rules::SPACE_TAB0),
        ]),
        kind: Some(SyntaxKind::AlignmentSeparator),
        root: false,
    },
    DocumentRule {
        rule: rules::BODY,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Rule(rules::SECTION)),
        ]),
        kind: Some(SyntaxKind::Body),
        root: false,
    },
    DocumentRule {
        rule: rules::CENTER_ALIGNMENT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::COLON),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DASH)),
            GrammarExpression::Rule(rules::COLON),
        ]),
        kind: Some(SyntaxKind::CenterAlignment),
        root: false,
    },
    DocumentRule {
        rule: rules::CHECK_LIST,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::CHECK_LIST_ITEM),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::CHECK_LIST_ITEM),
                GrammarExpression::Rule(rules::SUBLIST),
            ])),
        ]),
        kind: Some(SyntaxKind::CheckList),
        root: false,
    },
    DocumentRule {
        rule: rules::CHECK_LIST_ITEM,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::CHECKED_ITEM),
            GrammarExpression::Rule(rules::UNCHECKED_ITEM),
        ]),
        kind: Some(SyntaxKind::CheckListItem),
        root: false,
    },
    DocumentRule {
        rule: rules::CHECKED_ITEM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::DASH),
            GrammarExpression::Rule(rules::LEFT_BRACKET),
            GrammarExpression::Choice(&[
                GrammarExpression::Literal("x"),
                GrammarExpression::Literal("✓"),
                GrammarExpression::Literal("✗"),
            ]),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
        ]),
        kind: Some(SyntaxKind::CheckedItem),
        root: false,
    },
    DocumentRule {
        rule: rules::CITATION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_BRACKET),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::ALPHANUMERIC)),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::COLON),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::PARAGRAPH),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::Citation),
        root: false,
    },
    DocumentRule {
        rule: rules::CODE_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::CODEBLOCK_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Not(&GrammarExpression::Rule(rules::LEFT_BRACE)),
                GrammarExpression::Rule(rules::TEXT),
            ])),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::OPTION_MAP)),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::NEW_LINE),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Not(&GrammarExpression::Builtin("matching-codeblock-sigil")),
                GrammarExpression::Rule(rules::ANY),
            ])),
            GrammarExpression::Builtin("matching-codeblock-sigil"),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::CodeBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::CODE_TERMINAL,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Optional(&GrammarExpression::Sequence(&[
                GrammarExpression::Optional(&GrammarExpression::Rule(rules::SEMICOLON)),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::COMMENT),
            ])),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::NEW_LINE),
                GrammarExpression::Rule(rules::SEMICOLON),
                GrammarExpression::Peek(&GrammarExpression::Rule(rules::RIGHT_BRACE)),
                GrammarExpression::Peek(&GrammarExpression::Builtin("eof")),
                GrammarExpression::Peek(&GrammarExpression::Rule(rules::MIKA_SECTION_CLOSE)),
            ]),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::CodeTerminal),
        root: false,
    },
    DocumentRule {
        rule: rules::CONTEXT_SEND,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::VAR),
            GrammarExpression::Rule(rules::SEND_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
        ]),
        kind: Some(SyntaxKind::ContextSend),
        root: false,
    },
    DocumentRule {
        rule: rules::EMPHASIS,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::EMPHASIS_SIGIL),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
            GrammarExpression::Rule(rules::EMPHASIS_SIGIL),
        ]),
        kind: Some(SyntaxKind::Emphasis),
        root: false,
    },
    DocumentRule {
        rule: rules::EMPTY_PARAGRAPH,
        expression: GrammarExpression::Empty,
        kind: Some(SyntaxKind::EmptyParagraph),
        root: false,
    },
    DocumentRule {
        rule: rules::ENUM_DEFINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_ANGLE),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::RIGHT_ANGLE),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::ENUM_SEPARATOR),
                item: &GrammarExpression::Rule(rules::ENUM_VARIANT),
            },
        ]),
        kind: Some(SyntaxKind::EnumDefine),
        root: false,
    },
    DocumentRule {
        rule: rules::ENUM_VARIANT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::GRAVE)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::COLON)),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Optional(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::ENUM_VARIANT_KIND),
                GrammarExpression::Rule(rules::ENUM_VARIANT_INLINE_KIND),
            ])),
        ]),
        kind: Some(SyntaxKind::EnumVariant),
        root: false,
    },
    DocumentRule {
        rule: rules::ENUM_VARIANT_INLINE_KIND,
        expression: GrammarExpression::Rule(rules::KIND_ANNOTATION),
        kind: Some(SyntaxKind::EnumVariantInlineKind),
        root: false,
    },
    DocumentRule {
        rule: rules::ENUM_VARIANT_KIND,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Rule(rules::KIND_ANNOTATION),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
        ]),
        kind: Some(SyntaxKind::EnumVariantKind),
        root: false,
    },
    DocumentRule {
        rule: rules::ERROR_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::FLOAT_SIGIL)),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::ERROR_SIGIL),
                GrammarExpression::Rule(rules::ERROR_ALT_SIGIL),
            ]),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::ErrorBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::EVAL_INLINE_MECH_CODE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_BRACE),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::EXPRESSION),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::RIGHT_BRACE),
        ]),
        kind: Some(SyntaxKind::EvalInlineMechCode),
        root: false,
    },
    DocumentRule {
        rule: rules::FIGURE_ITEM,
        expression: GrammarExpression::Rule(rules::IMG),
        kind: Some(SyntaxKind::FigureItem),
        root: false,
    },
    DocumentRule {
        rule: rules::FIGURES,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::FIGURES_ROW)),
        kind: Some(SyntaxKind::Figures),
        root: false,
    },
    DocumentRule {
        rule: rules::FIGURES_ROW,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::BAR),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::FIGURE_ITEM),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::BAR),
            ])),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::FiguresRow),
        root: false,
    },
    DocumentRule {
        rule: rules::FLOAT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::FLOAT_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::SECTION_ELEMENT),
        ]),
        kind: Some(SyntaxKind::Float),
        root: false,
    },
    DocumentRule {
        rule: rules::FLOAT_SIGIL,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::FLOAT_LEFT),
            GrammarExpression::Rule(rules::FLOAT_RIGHT),
        ]),
        kind: Some(SyntaxKind::FloatSigil),
        root: false,
    },
    DocumentRule {
        rule: rules::FOOTNOTE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::FOOTNOTE_PREFIX),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Not(&GrammarExpression::Rule(rules::RIGHT_BRACKET)),
                GrammarExpression::Rule(rules::TEXT),
            ])),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::COLON),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::Footnote),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::HASHTAG),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::ARGUMENT_LIST)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::KIND_ANNOTATION)),
        ]),
        kind: Some(SyntaxKind::Fsm),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_ARM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::FSM_GUARD_ARM),
                GrammarExpression::Rule(rules::FSM_TRANSITION),
                GrammarExpression::Rule(rules::FSM_COMMENT_ARM),
            ]),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::FsmArm),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_BLOCK_TRANSITION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::TRANSITION_OPERATOR),
            GrammarExpression::Rule(rules::LEFT_BRACE),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::WHITESPACE0),
                GrammarExpression::Rule(rules::MECH_CODE_ALT),
                GrammarExpression::Optional(&GrammarExpression::Rule(rules::CODE_TERMINAL)),
            ])),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::RIGHT_BRACE),
        ]),
        kind: Some(SyntaxKind::FsmBlockTransition),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_COMMENT_ARM,
        expression: GrammarExpression::Rule(rules::COMMENT),
        kind: Some(SyntaxKind::FsmCommentArm),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_DECLARE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::FSM),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Rule(rules::FSM_PIPE),
        ]),
        kind: Some(SyntaxKind::FsmDeclare),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_GUARD,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::GUARD_OPERATOR),
            GrammarExpression::Rule(rules::PATTERN),
            GrammarExpression::OneOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::FSM_STATEMENT_TRANSITION),
                GrammarExpression::Rule(rules::FSM_STATE_TRANSITION),
                GrammarExpression::Rule(rules::FSM_OUTPUT),
                GrammarExpression::Rule(rules::FSM_ASYNC_TRANSITION),
                GrammarExpression::Rule(rules::FSM_BLOCK_TRANSITION),
            ])),
        ]),
        kind: Some(SyntaxKind::FsmGuard),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_GUARD_ARM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::PATTERN),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::FSM_GUARD)),
        ]),
        kind: Some(SyntaxKind::FsmGuardArm),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_IMPLEMENTATION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::HASHTAG),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::VAR),
            }),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Rule(rules::TRANSITION_OPERATOR),
            GrammarExpression::Rule(rules::FSM_VALUE),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::FSM_ARM)),
            GrammarExpression::Rule(rules::PERIOD),
        ]),
        kind: Some(SyntaxKind::FsmImplementation),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_SPECIFICATION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::HASHTAG),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::VAR),
            }),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::OUTPUT_OPERATOR)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::KIND_ANNOTATION)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::DEFINE_OPERATOR)),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::FSM_STATE_DEFINITION)),
            GrammarExpression::Rule(rules::PERIOD),
        ]),
        kind: Some(SyntaxKind::FsmSpecification),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_STATE_DEFINITION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::GUARD_OPERATOR),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::ATOM),
            GrammarExpression::Optional(&GrammarExpression::Rule(
                rules::FSM_STATE_DEFINITION_VARIABLES,
            )),
        ]),
        kind: Some(SyntaxKind::FsmStateDefinition),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_STATE_DEFINITION_VARIABLES,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::VAR),
            },
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
        ]),
        kind: Some(SyntaxKind::FsmStateDefinitionVariables),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_STATEMENT_TRANSITION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::TRANSITION_OPERATOR),
            GrammarExpression::Rule(rules::STATEMENT),
        ]),
        kind: Some(SyntaxKind::FsmStatementTransition),
        root: false,
    },
    DocumentRule {
        rule: rules::FSM_TRANSITION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::PATTERN),
            GrammarExpression::OneOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::FSM_BLOCK_TRANSITION),
                GrammarExpression::Rule(rules::FSM_STATEMENT_TRANSITION),
                GrammarExpression::Rule(rules::FSM_STATE_TRANSITION),
                GrammarExpression::Rule(rules::FSM_OUTPUT),
                GrammarExpression::Rule(rules::FSM_ASYNC_TRANSITION),
            ])),
        ]),
        kind: Some(SyntaxKind::FsmTransition),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_ARG,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::KIND_ANNOTATION),
        ]),
        kind: Some(SyntaxKind::FunctionArg),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_DEFINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::FUNCTION_ARG),
            }),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::FUNCTION_DEFINE_MATCH_ARMS),
                GrammarExpression::Rule(rules::FUNCTION_DEFINE_STATEMENTS),
            ]),
        ]),
        kind: Some(SyntaxKind::FunctionDefine),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_DEFINE_MATCH_ARMS,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::OUTPUT_OPERATOR),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::KIND_ANNOTATION),
            GrammarExpression::OneOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::WHITESPACE1),
                GrammarExpression::Rule(rules::STATEMENT_SEPARATOR),
            ])),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::FUNCTION_MATCH_ARM)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::PERIOD)),
        ]),
        kind: Some(SyntaxKind::FunctionDefineMatchArms),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_DEFINE_STATEMENTS,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::EQUAL),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::FUNCTION_OUT_ARGS),
                GrammarExpression::Rule(rules::FUNCTION_OUT_ARG),
            ]),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Choice(&[
                    GrammarExpression::Rule(rules::WHITESPACE1),
                    GrammarExpression::Rule(rules::STATEMENT_SEPARATOR),
                ]),
                item: &GrammarExpression::Rule(rules::STATEMENT),
            },
            GrammarExpression::Rule(rules::PERIOD),
        ]),
        kind: Some(SyntaxKind::FunctionDefineStatements),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_MATCH_ARM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::BOX_T_LEFT),
                GrammarExpression::Rule(rules::BOX_BL),
                GrammarExpression::Rule(rules::BAR),
            ]),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Sequence(&[
                    GrammarExpression::Rule(rules::PATTERN),
                    GrammarExpression::Rule(rules::WHITESPACE0),
                    GrammarExpression::Rule(rules::OUTPUT_OPERATOR),
                    GrammarExpression::Rule(rules::WHITESPACE0),
                    GrammarExpression::Rule(rules::EXPRESSION),
                ]),
                GrammarExpression::Rule(rules::EXPRESSION),
            ]),
            GrammarExpression::Optional(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::WHITESPACE1),
                GrammarExpression::Rule(rules::STATEMENT_SEPARATOR),
            ])),
        ]),
        kind: Some(SyntaxKind::FunctionMatchArm),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_OUT_ARG,
        expression: GrammarExpression::Rule(rules::FUNCTION_ARG),
        kind: Some(SyntaxKind::FunctionOutArg),
        root: false,
    },
    DocumentRule {
        rule: rules::FUNCTION_OUT_ARGS,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::FUNCTION_ARG),
            },
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
        ]),
        kind: Some(SyntaxKind::FunctionOutArgs),
        root: false,
    },
    DocumentRule {
        rule: rules::HIGHLIGHT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::HIGHLIGHT_SIGIL),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
            GrammarExpression::Rule(rules::HIGHLIGHT_SIGIL),
        ]),
        kind: Some(SyntaxKind::Highlight),
        root: false,
    },
    DocumentRule {
        rule: rules::HYPERLINK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_BRACKET),
            GrammarExpression::Rule(rules::INLINE_PARAGRAPH),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Not(&GrammarExpression::Rule(rules::RIGHT_PARENTHESIS)),
                GrammarExpression::Rule(rules::TEXT),
            ])),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
        ]),
        kind: Some(SyntaxKind::Hyperlink),
        root: false,
    },
    DocumentRule {
        rule: rules::IDEA_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::IDEA_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::IdeaBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::IMG,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::IMG_PREFIX),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::INLINE_PARAGRAPH)),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Not(&GrammarExpression::Rule(rules::RIGHT_PARENTHESIS)),
                GrammarExpression::Rule(rules::TEXT),
            ])),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::OPTION_MAP)),
        ]),
        kind: Some(SyntaxKind::Img),
        root: false,
    },
    DocumentRule {
        rule: rules::INFO_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::INFO_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::InfoBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::INLINE_MECH_CODE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_BRACE),
            GrammarExpression::Rule(rules::LEFT_BRACE),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::MECH_CODE_ALT),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::RIGHT_BRACE),
            GrammarExpression::Rule(rules::RIGHT_BRACE),
        ]),
        kind: Some(SyntaxKind::InlineMechCode),
        root: false,
    },
    DocumentRule {
        rule: rules::INLINE_PARAGRAPH,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::NEW_LINE)),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
        ])),
        kind: Some(SyntaxKind::InlineParagraph),
        root: false,
    },
    DocumentRule {
        rule: rules::INVARIANT_DEFINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::EXCLAMATION),
            GrammarExpression::Not(&GrammarExpression::Rule(rules::ASSIGN_OPERATOR)),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
        ]),
        kind: Some(SyntaxKind::InvariantDefine),
        root: false,
    },
    DocumentRule {
        rule: rules::KIND_DEFINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_ANGLE),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::RIGHT_ANGLE),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Rule(rules::KIND_ANNOTATION),
        ]),
        kind: Some(SyntaxKind::KindDefine),
        root: false,
    },
    DocumentRule {
        rule: rules::LEFT_ALIGNMENT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::COLON),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DASH)),
        ]),
        kind: Some(SyntaxKind::LeftAlignment),
        root: false,
    },
    DocumentRule {
        rule: rules::MATCH_EXPRESSION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::FACTOR),
            GrammarExpression::Rule(rules::QUESTION),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::MATCH_ARM)),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::PERIOD)),
        ]),
        kind: Some(SyntaxKind::MatchExpression),
        root: false,
    },
    DocumentRule {
        rule: rules::MECH_CODE,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::NOT_MECH_CODE)),
            GrammarExpression::Rule(rules::MECH_CODE_ALT),
            GrammarExpression::Rule(rules::CODE_TERMINAL),
        ])),
        kind: Some(SyntaxKind::MechCode),
        root: false,
    },
    DocumentRule {
        rule: rules::MECH_CODE_ALT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::BestChoice(&[
                GrammarExpression::Rule(rules::ACTIVATION_SCOPE),
                GrammarExpression::Rule(rules::FSM_SPECIFICATION),
                GrammarExpression::Rule(rules::FSM_IMPLEMENTATION),
                GrammarExpression::Rule(rules::FUNCTION_DEFINE),
                GrammarExpression::Rule(rules::MODULE_IMPORT),
                GrammarExpression::Rule(rules::STATEMENT),
                GrammarExpression::Rule(rules::EXPRESSION),
                GrammarExpression::Rule(rules::COMMENT),
            ]),
        ]),
        kind: Some(SyntaxKind::MechCodeAlt),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_LIST,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::ORDERED_LIST),
            GrammarExpression::Rule(rules::CHECK_LIST),
            GrammarExpression::Rule(rules::UNORDERED_LIST),
        ]),
        kind: Some(SyntaxKind::MechdownList),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_TABLE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::MECHDOWN_TABLE_WITH_HEADER),
                GrammarExpression::Rule(rules::MECHDOWN_TABLE_NO_HEADER),
            ]),
        ]),
        kind: Some(SyntaxKind::MechdownTable),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_TABLE_HEADER,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::BAR),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::INLINE_PARAGRAPH),
            ])),
            GrammarExpression::Rule(rules::BAR),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::BAR),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::ALIGNMENT_SEPARATOR),
            ])),
            GrammarExpression::Rule(rules::BAR),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::MechdownTableHeader),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_TABLE_NO_HEADER,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Rule(
            rules::MECHDOWN_TABLE_ROW,
        )),
        kind: Some(SyntaxKind::MechdownTableNoHeader),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_TABLE_ROW,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::BAR),
            GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Choice(&[
                    GrammarExpression::Sequence(&[
                        GrammarExpression::Rule(rules::SPACE_TAB0),
                        GrammarExpression::Rule(rules::INLINE_PARAGRAPH),
                    ]),
                    GrammarExpression::Sequence(&[
                        GrammarExpression::Rule(rules::SPACE_TAB1),
                        GrammarExpression::Rule(rules::EMPTY_PARAGRAPH),
                    ]),
                ]),
                GrammarExpression::Rule(rules::BAR),
            ])),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::MechdownTableRow),
        root: false,
    },
    DocumentRule {
        rule: rules::MECHDOWN_TABLE_WITH_HEADER,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::MECHDOWN_TABLE_HEADER),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::MECHDOWN_TABLE_ROW)),
        ]),
        kind: Some(SyntaxKind::MechdownTableWithHeader),
        root: false,
    },
    DocumentRule {
        rule: rules::MICRO_MIKA,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::MIKA_ARM_LEFT),
            GrammarExpression::Rule(rules::MIKA_NOSE),
            GrammarExpression::Rule(rules::MIKA_ARM_RIGHT),
        ]),
        kind: Some(SyntaxKind::MicroMika),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::MINI_MIKA),
                GrammarExpression::Rule(rules::MICRO_MIKA),
            ]),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::MIKA_SECTION)),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::Mika),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_ARM_LEFT,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Literal("Ɔ∞"),
            GrammarExpression::Literal("›─"),
            GrammarExpression::Literal("›⌣"),
            GrammarExpression::Literal("·¬"),
            GrammarExpression::Literal("-◡"),
            GrammarExpression::Literal("ᗑ"),
            GrammarExpression::Literal("ᕦ"),
            GrammarExpression::Literal("~"),
            GrammarExpression::Literal("⌣"),
            GrammarExpression::Literal("╭"),
            GrammarExpression::Literal("⸌"),
            GrammarExpression::Literal("⸸"),
            GrammarExpression::Literal("─"),
            GrammarExpression::Literal("ᓂ"),
            GrammarExpression::Literal("ᓇ"),
            GrammarExpression::Literal("╰"),
        ]),
        kind: Some(SyntaxKind::MikaArmLeft),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_ARM_RIGHT,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Literal("∞C"),
            GrammarExpression::Literal("─‹"),
            GrammarExpression::Literal("⌣‹"),
            GrammarExpression::Literal("⌐·"),
            GrammarExpression::Literal("◡-"),
            GrammarExpression::Literal("ᗑ"),
            GrammarExpression::Literal("ᕤ"),
            GrammarExpression::Literal("~"),
            GrammarExpression::Literal("⌣"),
            GrammarExpression::Literal("╮"),
            GrammarExpression::Literal("⸍"),
            GrammarExpression::Literal("ᗢ"),
            GrammarExpression::Literal("─"),
            GrammarExpression::Literal("ᓀ"),
            GrammarExpression::Literal("ᓄ"),
            GrammarExpression::Literal("╯"),
        ]),
        kind: Some(SyntaxKind::MikaArmRight),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_EXPRESSION_INNER,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::MIKA_EYE_LEFT),
            GrammarExpression::Rule(rules::MIKA_NOSE),
            GrammarExpression::Rule(rules::MIKA_EYE_RIGHT),
        ]),
        kind: Some(SyntaxKind::MikaExpressionInner),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_EYE_LEFT,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Literal("⌐▰"),
            GrammarExpression::Literal("ˆ"),
            GrammarExpression::Literal("ಠ"),
            GrammarExpression::Literal("╥"),
            GrammarExpression::Literal("⋇"),
            GrammarExpression::Literal("✖"),
            GrammarExpression::Literal("≻"),
            GrammarExpression::Literal("ᗒ"),
            GrammarExpression::Literal("ㆆ"),
            GrammarExpression::Literal("◜"),
            GrammarExpression::Literal("˙"),
            GrammarExpression::Literal("⚆"),
            GrammarExpression::Literal("☉"),
            GrammarExpression::Literal("◠"),
            GrammarExpression::Literal("◡̀"),
            GrammarExpression::Literal("◕"),
            GrammarExpression::Literal("◞"),
            GrammarExpression::Literal("Ͼ"),
            GrammarExpression::Literal("⹇"),
            GrammarExpression::Literal("ᗣ"),
            GrammarExpression::Literal("≖"),
            GrammarExpression::Literal("°"),
            GrammarExpression::Literal("ᗩ"),
            GrammarExpression::Literal("¬"),
            GrammarExpression::Literal("◉"),
        ]),
        kind: Some(SyntaxKind::MikaEyeLeft),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_EYE_RIGHT,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Literal("ˆ"),
            GrammarExpression::Literal("ಠ"),
            GrammarExpression::Literal("╥"),
            GrammarExpression::Literal("⋇"),
            GrammarExpression::Literal("✖"),
            GrammarExpression::Literal("≺"),
            GrammarExpression::Literal("ᗕ"),
            GrammarExpression::Literal("ㆆ"),
            GrammarExpression::Literal("◝"),
            GrammarExpression::Literal("˙"),
            GrammarExpression::Literal("⚆"),
            GrammarExpression::Literal("☉"),
            GrammarExpression::Literal("◠"),
            GrammarExpression::Literal("◡́"),
            GrammarExpression::Literal("◕"),
            GrammarExpression::Literal("◟"),
            GrammarExpression::Literal("Ͽ"),
            GrammarExpression::Literal("▰"),
            GrammarExpression::Literal("⹇"),
            GrammarExpression::Literal("ᗣ"),
            GrammarExpression::Literal("≖"),
            GrammarExpression::Literal("°"),
            GrammarExpression::Literal("ᗩ"),
            GrammarExpression::Literal("¬"),
            GrammarExpression::Literal("◉"),
        ]),
        kind: Some(SyntaxKind::MikaEyeRight),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_NOSE,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Literal("⦿"),
            GrammarExpression::Literal("◯"),
            GrammarExpression::Literal("⊕"),
            GrammarExpression::Literal("∘"),
            GrammarExpression::Literal("⦾"),
            GrammarExpression::Literal("⊖"),
            GrammarExpression::Literal("⦵"),
            GrammarExpression::Literal("⊗"),
            GrammarExpression::Literal("⏺"),
            GrammarExpression::Literal("⍜"),
            GrammarExpression::Literal("⬢"),
            GrammarExpression::Literal("⬟"),
            GrammarExpression::Literal("⬣"),
            GrammarExpression::Literal("⎔"),
        ]),
        kind: Some(SyntaxKind::MikaNose),
        root: false,
    },
    DocumentRule {
        rule: rules::MIKA_SECTION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::MIKA_SECTION_OPEN),
            GrammarExpression::Rule(rules::SECTION),
            GrammarExpression::Rule(rules::MIKA_SECTION_CLOSE),
        ]),
        kind: Some(SyntaxKind::MikaSection),
        root: false,
    },
    DocumentRule {
        rule: rules::MINI_MIKA,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::MIKA_ARM_LEFT)),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::MIKA_ARM_RIGHT)),
            GrammarExpression::Rule(rules::MIKA_EXPRESSION_INNER),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::MIKA_ARM_LEFT)),
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::MIKA_ARM_RIGHT)),
        ]),
        kind: Some(SyntaxKind::MiniMika),
        root: false,
    },
    DocumentRule {
        rule: rules::NO_ALIGNMENT,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DASH)),
        kind: Some(SyntaxKind::NoAlignment),
        root: false,
    },
    DocumentRule {
        rule: rules::NOT_MECH_CODE,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::QUESTION_BLOCK),
            GrammarExpression::Rule(rules::INFO_BLOCK),
            GrammarExpression::Rule(rules::SUCCESS_BLOCK),
            GrammarExpression::Rule(rules::WARNING_BLOCK),
            GrammarExpression::Rule(rules::ERROR_BLOCK),
            GrammarExpression::Rule(rules::IDEA_BLOCK),
            GrammarExpression::Rule(rules::IMG),
            GrammarExpression::Rule(rules::MIKA_SECTION_CLOSE),
            GrammarExpression::Rule(rules::FLOAT),
        ]),
        kind: Some(SyntaxKind::NotMechCode),
        root: false,
    },
    DocumentRule {
        rule: rules::OP_ASSIGN,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::SLICE_REF),
            GrammarExpression::Not(&GrammarExpression::Rule(rules::DEFINE_OPERATOR)),
            GrammarExpression::Rule(rules::OP_ASSIGN_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
        ]),
        kind: Some(SyntaxKind::OpAssign),
        root: false,
    },
    DocumentRule {
        rule: rules::OPTION_MAP,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_BRACE),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::OPTION_MAPPING)),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::RIGHT_BRACE),
        ]),
        kind: Some(SyntaxKind::OptionMap),
        root: false,
    },
    DocumentRule {
        rule: rules::OPTION_MAPPING,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::IDENTIFIER),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::COLON),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::OPTION_VALUE),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::COMMA)),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::OptionMapping),
        root: false,
    },
    DocumentRule {
        rule: rules::OPTION_VALUE,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::STRING),
            GrammarExpression::Rule(rules::IDENTIFIER),
        ]),
        kind: Some(SyntaxKind::OptionValue),
        root: false,
    },
    DocumentRule {
        rule: rules::ORDERED_LIST,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::ORDERED_LIST_ITEM),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::ORDERED_LIST_ITEM),
                GrammarExpression::Rule(rules::SUBLIST),
            ])),
        ]),
        kind: Some(SyntaxKind::OrderedList),
        root: false,
    },
    DocumentRule {
        rule: rules::ORDERED_LIST_ITEM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::NUMBER),
            GrammarExpression::Rule(rules::PERIOD),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
        ]),
        kind: Some(SyntaxKind::OrderedListItem),
        root: false,
    },
    DocumentRule {
        rule: rules::PARAGRAPH,
        expression: GrammarExpression::OneOrMore(&GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::NEW_LINE),
                GrammarExpression::Rule(rules::MIKA_SECTION_CLOSE),
                GrammarExpression::Rule(rules::IDEA_SIGIL),
            ])),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
        ])),
        kind: Some(SyntaxKind::Paragraph),
        root: false,
    },
    DocumentRule {
        rule: rules::PARAGRAPH_ELEMENT,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::HYPERLINK),
            GrammarExpression::Rule(rules::REFERENCE),
            GrammarExpression::Rule(rules::SECTION_REFERENCE),
            GrammarExpression::Rule(rules::RAW_HYPERLINK),
            GrammarExpression::Rule(rules::HIGHLIGHT),
            GrammarExpression::Rule(rules::FOOTNOTE_REFERENCE),
            GrammarExpression::Rule(rules::INLINE_MECH_CODE),
            GrammarExpression::Rule(rules::EVAL_INLINE_MECH_CODE),
            GrammarExpression::Rule(rules::INLINE_EQUATION),
            GrammarExpression::Rule(rules::PARAGRAPH_TEXT),
            GrammarExpression::Rule(rules::STRONG),
            GrammarExpression::Rule(rules::EMPHASIS),
            GrammarExpression::Rule(rules::INLINE_CODE),
            GrammarExpression::Rule(rules::STRIKETHROUGH),
            GrammarExpression::Rule(rules::UNDERLINE),
        ]),
        kind: Some(SyntaxKind::ParagraphElement),
        root: false,
    },
    DocumentRule {
        rule: rules::PARAGRAPH_NEWLINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::PARAGRAPH),
            GrammarExpression::Rule(rules::NEW_LINE),
        ]),
        kind: Some(SyntaxKind::ParagraphNewline),
        root: false,
    },
    DocumentRule {
        rule: rules::PARSE,
        expression: GrammarExpression::Rule(rules::PARSE_MECH),
        kind: Some(SyntaxKind::Document),
        root: true,
    },
    DocumentRule {
        rule: rules::PARSE_MECH,
        expression: GrammarExpression::Rule(rules::PROGRAM),
        kind: None,
        root: false,
    },
    DocumentRule {
        rule: rules::PROGRAM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::TITLE)),
            GrammarExpression::Rule(rules::BODY),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: None,
        root: false,
    },
    DocumentRule {
        rule: rules::PROMPT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::PROMPT_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::SECTION_ELEMENT),
        ]),
        kind: Some(SyntaxKind::Prompt),
        root: false,
    },
    DocumentRule {
        rule: rules::QUESTION_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::QUESTION_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::QuestionBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::QUOTE_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::FLOAT_SIGIL)),
            GrammarExpression::Not(&GrammarExpression::Rule(rules::PROMPT_SIGIL)),
            GrammarExpression::Rule(rules::QUOTE_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::QuoteBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::RIGHT_ALIGNMENT,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DASH)),
            GrammarExpression::Rule(rules::COLON),
        ]),
        kind: Some(SyntaxKind::RightAlignment),
        root: false,
    },
    DocumentRule {
        rule: rules::SECTION,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::UL_SUBTITLE)),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::MIKA),
                GrammarExpression::Rule(rules::MECH_CODE),
                GrammarExpression::Sequence(&[
                    GrammarExpression::Rule(rules::SECTION_ELEMENT),
                    GrammarExpression::ZeroOrMore(&GrammarExpression::Rule(rules::BLANK_LINE)),
                ]),
            ])),
        ]),
        kind: Some(SyntaxKind::Section),
        root: false,
    },
    DocumentRule {
        rule: rules::SECTION_ELEMENT,
        expression: GrammarExpression::BestChoice(&[
            GrammarExpression::Rule(rules::MECHDOWN_LIST),
            GrammarExpression::Rule(rules::PROMPT),
            GrammarExpression::Rule(rules::FOOTNOTE),
            GrammarExpression::Rule(rules::CITATION),
            GrammarExpression::Rule(rules::ABSTRACT_EL),
            GrammarExpression::Rule(rules::IMG),
            GrammarExpression::Rule(rules::FIGURES),
            GrammarExpression::Rule(rules::EQUATION),
            GrammarExpression::Rule(rules::MECHDOWN_TABLE),
            GrammarExpression::Rule(rules::FLOAT),
            GrammarExpression::Rule(rules::QUOTE_BLOCK),
            GrammarExpression::Rule(rules::CODE_BLOCK),
            GrammarExpression::Rule(rules::THEMATIC_BREAK),
            GrammarExpression::Rule(rules::SUBTITLE),
            GrammarExpression::Rule(rules::QUESTION_BLOCK),
            GrammarExpression::Rule(rules::INFO_BLOCK),
            GrammarExpression::Rule(rules::SUCCESS_BLOCK),
            GrammarExpression::Rule(rules::WARNING_BLOCK),
            GrammarExpression::Rule(rules::ERROR_BLOCK),
            GrammarExpression::Rule(rules::IDEA_BLOCK),
            GrammarExpression::Rule(rules::PARAGRAPH),
        ]),
        kind: Some(SyntaxKind::SectionElement),
        root: false,
    },
    DocumentRule {
        rule: rules::SLICE_REF,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::PREFIXED_CONTEXT_PATH),
                GrammarExpression::Optional(&GrammarExpression::Rule(rules::SUBSCRIPT)),
            ]),
            GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::IDENTIFIER),
                GrammarExpression::Optional(&GrammarExpression::Rule(rules::SUBSCRIPT)),
            ]),
        ]),
        kind: Some(SyntaxKind::SliceRef),
        root: false,
    },
    DocumentRule {
        rule: rules::STATEMENT,
        expression: GrammarExpression::BestChoice(&[
            GrammarExpression::Rule(rules::IMPORT_DECLARATION),
            GrammarExpression::Rule(rules::EXPORT_DECLARATION),
            GrammarExpression::Rule(rules::CONTEXT_DECLARATION),
            GrammarExpression::Rule(rules::FSM_DECLARE),
            GrammarExpression::Rule(rules::INVARIANT_DEFINE),
            GrammarExpression::Rule(rules::CONTEXT_SEND),
            GrammarExpression::Rule(rules::VARIABLE_DEFINE),
            GrammarExpression::Rule(rules::VARIABLE_ASSIGN),
            GrammarExpression::Rule(rules::OP_ASSIGN),
            GrammarExpression::Rule(rules::ENUM_DEFINE),
            GrammarExpression::Rule(rules::TUPLE_DESTRUCTURE),
            GrammarExpression::Rule(rules::KIND_DEFINE),
        ]),
        kind: Some(SyntaxKind::Statement),
        root: false,
    },
    DocumentRule {
        rule: rules::STRIKETHROUGH,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::TILDE),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
            GrammarExpression::Rule(rules::TILDE),
        ]),
        kind: Some(SyntaxKind::Strikethrough),
        root: false,
    },
    DocumentRule {
        rule: rules::STRONG,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::STRONG_SIGIL),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
            GrammarExpression::Rule(rules::STRONG_SIGIL),
        ]),
        kind: Some(SyntaxKind::Strong),
        root: false,
    },
    DocumentRule {
        rule: rules::SUBLIST,
        expression: GrammarExpression::Choice(&[
            GrammarExpression::Rule(rules::ORDERED_LIST),
            GrammarExpression::Rule(rules::CHECK_LIST),
            GrammarExpression::Rule(rules::UNORDERED_LIST),
        ]),
        kind: Some(SyntaxKind::Sublist),
        root: false,
    },
    DocumentRule {
        rule: rules::SUBTITLE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::ERROR_SIGIL),
                GrammarExpression::Rule(rules::INFO_SIGIL),
            ])),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::PERIOD),
                item: &GrammarExpression::Choice(&[
                    GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::ALPHA)),
                    GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DIGIT)),
                ]),
            },
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::Subtitle),
        root: false,
    },
    DocumentRule {
        rule: rules::SUCCESS_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::FLOAT_SIGIL)),
            GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::SUCCESS_SIGIL),
                GrammarExpression::Rule(rules::SUCCESS_CHECK_SIGIL),
            ]),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::SuccessBlock),
        root: false,
    },
    DocumentRule {
        rule: rules::TABLE_COLUMN,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::EXPRESSION),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Optional(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::COMMA),
                GrammarExpression::Rule(rules::TABLE_SEPARATOR),
            ])),
            GrammarExpression::Rule(rules::SPACE_TAB0),
        ]),
        kind: Some(SyntaxKind::TableColumn),
        root: false,
    },
    DocumentRule {
        rule: rules::TITLE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::TEXT)),
            GrammarExpression::Rule(rules::NEW_LINE),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::EQUAL)),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Optional(&GrammarExpression::Rule(rules::TITLE_FRONT_MATTER)),
        ]),
        kind: Some(SyntaxKind::Title),
        root: false,
    },
    DocumentRule {
        rule: rules::TITLE_FRONT_MATTER,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::ZeroOrMore(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::IDENTIFIER),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Rule(rules::COLON),
                GrammarExpression::Rule(rules::SPACE_TAB0),
                GrammarExpression::Choice(&[
                    GrammarExpression::Sequence(&[
                        GrammarExpression::Choice(&[
                            GrammarExpression::Rule(rules::IMG),
                            GrammarExpression::Rule(rules::FIGURES),
                        ]),
                        GrammarExpression::Rule(rules::WHITESPACE0),
                    ]),
                    GrammarExpression::Sequence(&[
                        GrammarExpression::Rule(rules::INLINE_PARAGRAPH),
                        GrammarExpression::Rule(rules::NEW_LINE),
                    ]),
                ]),
            ])),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::EQUAL)),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::TitleFrontMatter),
        root: false,
    },
    DocumentRule {
        rule: rules::TUPLE_DESTRUCTURE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
            GrammarExpression::Separated {
                separator: &GrammarExpression::Rule(rules::LIST_SEPARATOR),
                item: &GrammarExpression::Rule(rules::IDENTIFIER),
            },
            GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            GrammarExpression::Rule(rules::DEFINE_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
        ]),
        kind: Some(SyntaxKind::TupleDestructure),
        root: false,
    },
    DocumentRule {
        rule: rules::UL_SUBTITLE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::OneOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::DIGIT_TOKEN),
                GrammarExpression::Rule(rules::ALPHA_TOKEN),
            ])),
            GrammarExpression::Rule(rules::PERIOD),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::DASH)),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::NEW_LINE),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::Rule(rules::WHITESPACE0),
        ]),
        kind: Some(SyntaxKind::UlSubtitle),
        root: false,
    },
    DocumentRule {
        rule: rules::UNCHECKED_ITEM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::DASH),
            GrammarExpression::Rule(rules::LEFT_BRACKET),
            GrammarExpression::Rule(rules::WHITESPACE0),
            GrammarExpression::Rule(rules::RIGHT_BRACKET),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
        ]),
        kind: Some(SyntaxKind::UncheckedItem),
        root: false,
    },
    DocumentRule {
        rule: rules::UNDERLINE,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::UNDERSCORE),
            GrammarExpression::Rule(rules::PARAGRAPH_ELEMENT),
            GrammarExpression::Rule(rules::UNDERSCORE),
        ]),
        kind: Some(SyntaxKind::Underline),
        root: false,
    },
    DocumentRule {
        rule: rules::UNORDERED_LIST,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::UNORDERED_LIST_ITEM),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Choice(&[
                GrammarExpression::Rule(rules::UNORDERED_LIST_ITEM),
                GrammarExpression::Rule(rules::SUBLIST),
            ])),
        ]),
        kind: Some(SyntaxKind::UnorderedList),
        root: false,
    },
    DocumentRule {
        rule: rules::UNORDERED_LIST_ITEM,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::DASH),
            GrammarExpression::Optional(&GrammarExpression::Sequence(&[
                GrammarExpression::Rule(rules::LEFT_PARENTHESIS),
                GrammarExpression::Rule(rules::EMOJI),
                GrammarExpression::Rule(rules::RIGHT_PARENTHESIS),
            ])),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::SPACE)),
            GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE),
            GrammarExpression::ZeroOrMore(&GrammarExpression::Rule(rules::NEW_LINE)),
        ]),
        kind: Some(SyntaxKind::UnorderedListItem),
        root: false,
    },
    DocumentRule {
        rule: rules::VARIABLE_ASSIGN,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Rule(rules::SLICE_REF),
            GrammarExpression::Not(&GrammarExpression::Rule(rules::DEFINE_OPERATOR)),
            GrammarExpression::Rule(rules::ASSIGN_OPERATOR),
            GrammarExpression::Rule(rules::EXPRESSION),
        ]),
        kind: Some(SyntaxKind::VariableAssign),
        root: false,
    },
    DocumentRule {
        rule: rules::WARNING_BLOCK,
        expression: GrammarExpression::Sequence(&[
            GrammarExpression::Not(&GrammarExpression::Rule(rules::FLOAT_SIGIL)),
            GrammarExpression::Rule(rules::WARNING_SIGIL),
            GrammarExpression::Rule(rules::SPACE_TAB0),
            GrammarExpression::OneOrMore(&GrammarExpression::Rule(rules::PARAGRAPH_NEWLINE)),
        ]),
        kind: Some(SyntaxKind::WarningBlock),
        root: false,
    },
];
