[package]
name = "mech-native-kernel-prototype"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libloading = "0.8.9"
mech-build = { path = "../../../../src/build", default-features = false }
mech-core = { path = "../../../../src/core", default-features = false }
mech-engine = { path = "../../../../src/engine", default-features = false, features = ["native-kernel-prototype"] }
mech-stdlib = { path = "../../../../src/stdlib", default-features = false, features = ["full_compiler"] }
nalgebra = "0.34"

[workspace]

[patch.crates-io]
mech-bytecode = { path = "../../../../src/bytecode" }
mech-core = { path = "../../../../src/core" }
mech-engine = { path = "../../../../src/engine" }
mech-syntax = { path = "../../../../src/syntax" }
mech-stdlib = { path = "../../../../src/stdlib" }
mech-math = { path = "../../../../machines/math" }
mech-compare = { path = "../../../../machines/compare" }
mech-logic = { path = "../../../../machines/logic" }
mech-range = { path = "../../../../machines/range" }
mech-matrix = { path = "../../../../machines/matrix" }
mech-runtime = { path = "../../../../src/runtime" }
mech-set = { path = "../../../../machines/set" }
mech-string = { path = "../../../../machines/string" }
mech-stats = { path = "../../../../machines/stats" }
mech-combinatorics = { path = "../../../../machines/combinatorics" }
