#!/usr/bin/env python3
"""Record completed native proof output and exact executable/source identities."""
import argparse,hashlib,json,platform,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--exit-code',type=int,required=True);p.add_argument('--binary',type=Path,required=True);args=p.parse_args()
log=ROOT/'audit/v04/evidence/trust-native-full.log';text=log.read_text()
turns=[dict(zip(['turn','expected','source_artifact','decoded_bytecode','epoch'],map(int,row))) for row in re.findall(r'^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+COMMIT\s*$',text,re.M)]
expected=[5,13,29,61,125,253,509]
passed=args.exit_code==0 and 'ALL CLAIMED CHECKS PASSED' in text and [x['source_artifact'] for x in turns]==expected and all(t['source_artifact']==t['decoded_bytecode']==t['expected'] for t in turns)
hash_file=lambda path:hashlib.sha256(path.read_bytes()).hexdigest()
files=sorted(set(['Cargo.toml','examples/r_stack_trust_proof.rs','examples/r-stack-proof/trust-program.mec','examples/r-stack-proof/perturbed-program.mec','scripts/demo-r-stack.sh']+[path for path in subprocess.check_output(['git','diff','--name-only'],cwd=ROOT,text=True).splitlines() if path.startswith(('src/','hosts/','machines/'))]))
result={'status':'passed' if passed else 'failed','source_commit':'c4777b7015fe8ff47fdfa48d18606c49aace7d97','absorbed_pr':'https://github.com/mech-lang/mech/pull/829','absorbed_revision':'9ae5c00e0184fe341d2ff2bdc590ede712009d2f','source_modifications':{path:hash_file(ROOT/path) for path in files},'scope':'native canonical parser and semantic frontend, source and decoded artifacts, engine resident primitive execution','command':'CARGO_TARGET_DIR=/private/tmp/mech-v04-target-product cargo run -p mech --locked --offline --no-default-features --example r-stack-trust-proof --features r_stack_trust_proof -- --dump all','features':'r_stack_trust_proof','default_features':False,'exit_code':args.exit_code,'binary':{'path':str(args.binary),'sha256':hash_file(args.binary)},'environment':{'platform':platform.platform(),'rustc':subprocess.check_output(['rustc','--version'],text=True).strip()},'source':(ROOT/'examples/r-stack-proof/trust-program.mec').read_text(),'source_artifact_revision':re.search(r'artifact revision\s*:\s*([0-9a-f]+)',text).group(1) if re.search(r'artifact revision\s*:\s*([0-9a-f]+)',text) else None,'turns':turns,'checks':re.findall(r'^\[PASS\] (.+)$',text,re.M),'perturbation':{'expected':[7,25,79],'passed':'resident outputs: PASS — 7, 25, 79' in text},'missing_catalog_rejected':'missing catalog: PASS — activation rejected' in text,'full_transcript':{'path':'audit/v04/evidence/trust-native-full.log','sha256':hash_file(log)}}
result.update({'id':'E-TRUST-NATIVE','claim':'Source recurrence and perturbation, artifact/bytecode receipt equality, and isolated rejection paths','contract':'examples/r-stack-proof/README.md','evidence_level':'native-execution','outcome':result['status'],'artifact_identity':result['binary']})
(ROOT/'audit/v04/evidence/trust-native.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'status':result['status'],'turns':len(turns),'checks':len(result['checks'])}));raise SystemExit(0 if passed else 1)
