[package]
name = "mech-range"
version = "0.3.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Range library for the Mech language"
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-machines/range"
keywords = ["mech", "language", "programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2024"

[badges]
gitlab = { repository = "mech-lang/machines/range", branch = "main" }
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["rlib"]

[features]
no_std = ["mech-core/no_std"]

default = []
runtime = ["mech-core/functions"]
source = ["runtime"]
semantic-compiler = ["runtime", "mech-core/semantic-compiler"]
compiler = ["semantic-compiler"]
native-plan = ["runtime", "mech-core/native-plan"]
native-link = ["runtime"]
standard_values = ["f64", "row_vectord", "matrixd"]
standard_operations = [
  "inclusive", "exclusive", "inclusive_increment", "exclusive_increment",
]
standard_runtime = ["runtime", "standard_values", "standard_operations"]
standard_source = ["standard_runtime", "source"]
standard_compiler = ["standard_source", "compiler"]
full_values = [
  "u8", "u16", "u32", "u64", "u128",
  "i8", "i16", "i32", "i64", "i128", "f32", "f64",
  "matrix1", "row_vector2", "row_vector3", "row_vector4", "row_vectord", "matrixd",
]
full_operations = [
  "inclusive", "exclusive", "inclusive_increment", "exclusive_increment",
]
full_runtime = ["runtime", "full_values", "full_operations"]
full_source = ["full_runtime", "source"]
full_compiler = ["full_source", "compiler"]

range_default = ["inclusive", "exclusive"]
range = ["runtime", "matrix", "dep:num-traits", "mech-core/range"]
inclusive = ["runtime", "range"]
exclusive = ["runtime", "range"]
inclusive_increment = ["runtime", "inclusive"]
exclusive_increment = ["runtime", "exclusive"]

# Numbers
numbers = ["mech-core/numbers"]
signed_ints = ["numbers", "mech-core/signed_ints"]
unsigned_ints = ["numbers", "mech-core/unsigned_ints"]
floats = ["numbers", "mech-core/floats"]
u8 = ["unsigned_ints", "mech-core/u8"]
u16 = ["unsigned_ints", "mech-core/u16"]
u32 = ["unsigned_ints", "mech-core/u32"]
u64 = ["unsigned_ints", "mech-core/u64"]
u128 = ["unsigned_ints", "mech-core/u128"]
i8 = ["signed_ints", "mech-core/i8"]
i16 = ["signed_ints", "mech-core/i16"]
i32 = ["signed_ints", "mech-core/i32"]
i64 = ["signed_ints", "mech-core/i64"]
i128 = ["signed_ints", "mech-core/i128"]
f32 = ["floats", "mech-core/f32"]
f64 = ["floats", "mech-core/f64"]

# Matrix
matrix = ["nalgebra", "mech-core/matrix"]
row_vector4 = ["matrix", "mech-core/row_vector4"]
row_vector3 = ["matrix", "mech-core/row_vector3"]
row_vector2 = ["matrix", "mech-core/row_vector2"]
matrix1 = ["matrix", "mech-core/matrix1"]
row_vectord =["matrix",  "mech-core/row_vectord"]
matrixd = ["matrix",  "mech-core/matrixd"]

[dependencies]
mech-core = { path = "../../src/core", version = "0.3.5", default-features = false }

paste = "1.0.15"
nalgebra = {version="0.34.1", optional = true}

[dependencies.num-traits]
version = "0.2.19"
default-features = false
features = ["libm"]
optional = true

[workspace]
