[package]
name = "mech-logic"
version = "0.3.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Logic library for the Mech language"
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-machines/logic"
keywords = ["mech", "language", "programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2024"

[badges]
gitlab = { repository = "mech-lang/machines/logic", branch = "main" }
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["rlib"]

[features]
no_std = ["mech-core/no_std"]

default = ["compiler_default"]
runtime = ["mech-core/functions"]
source = ["runtime"]
compiler = ["runtime", "mech-core/compiler"]
native-plan = ["runtime", "mech-core/native-plan"]
native-link = ["runtime"]
standard_values = [
  "bool", "matrix1", "matrix2", "matrix3", "matrix4", "matrix2x3", "matrix3x2",
  "row_vector2", "row_vector3", "row_vector4",
  "vector2", "vector3", "vector4", "row_vectord", "vectord", "matrixd",
]
runtime_default = ["runtime", "standard_values", "logic_default"]
source_default = ["runtime_default", "source"]
compiler_default = ["source_default", "compiler"]

logic_default = ["and", "or", "not", "xor"]
logic = ["runtime", "bool"]
and = ["runtime", "logic"]
or = ["runtime", "logic"]
not = ["runtime", "logic"]
xor = ["runtime", "logic"]

bool = ["mech-core/bool"]

# Matrix
matrix = ["nalgebra", "mech-core/matrix"]
row_vector4 = ["matrix", "mech-core/row_vector4"]
row_vector3 = ["matrix", "mech-core/row_vector3"]
row_vector2 = ["matrix", "mech-core/row_vector2"]
vector4 = ["matrix", "mech-core/vector4"]
vector3 = ["matrix", "mech-core/vector3"]
vector2 = ["matrix", "mech-core/vector2"]
matrix4 = ["matrix", "mech-core/matrix4"]
matrix3 = ["matrix", "mech-core/matrix3"]
matrix2 = ["matrix", "mech-core/matrix2", "mech-core/matrix"]
matrix1 = ["matrix", "mech-core/matrix1"]
matrix2x3 = ["matrix", "mech-core/matrix2x3"]
matrix3x2 = ["matrix", "mech-core/matrix3x2"]
row_vectord =["matrix",  "mech-core/row_vectord"]
vectord = ["matrix",  "mech-core/vectord"]
matrixd = ["matrix",  "mech-core/matrixd"]

[dependencies]
mech-core = { path = "../../src/core", version = "0.3.5", default-features = false }

paste = "1.0.15"
nalgebra = {version="0.34.1", optional = true}

[workspace]
