use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;

use mech_build::selected_planning_host_factory;
use mech_core::{
    BytecodeInstruction, ModuleManifestConfig, ModuleManifestExportConfig,
    ModuleManifestExportKind, ParsedProgram,
};
use mech_engine::{CanonicalSourceFrontend, encode_program_artifact_bytecode_v1};
use mech_syntax::document::parser::{canonical::parse_canonical_phase_2i_rule_for_test, rules};
use mech_syntax::document::{
    AstNode, DocumentId, ExpressionSyntax, ParseConfig, Revision, SyntaxKind, SyntaxNode,
    TextSnapshot,
};
use mech_native_live_host_fixture::{
    TEST_LIVE_BASE_URI, TEST_LIVE_CONTEXT, TEST_LIVE_INSTANCE, TEST_LIVE_PATH, TEST_LIVE_PROVIDER,
    TEST_LIVE_OUTPUT_BASE_URI, TEST_LIVE_OUTPUT_CONTEXT, TEST_LIVE_RECORD_PATH,
    TEST_LIVE_TUPLE_PATH, TestLiveHostFactory, empty_settings,
};
use mech_runtime::{
    ConfigValue, HostInstanceConfig, RunResourceGrantConfig, RuntimeBuilder,
};

fn main() {
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    let [output, functions_output, mode, source] = arguments.as_slice() else {
        panic!(
            "usage: bytecode-v1-source-generator <output.mecb> <functions.json> <mode> <source>"
        );
    };
    let bytecode = match mode.as_str() {
        "standard" => compile_standard(&source),
        "structural-match" => compile_structural_match(&source),
        "cli" => compile_source_fixture(cli_builder(), &source),
        "console" | "time" | "timer" | "scene" | "robot-arm" => {
            compile_source_fixture(host_builder(&mode), &source)
        }
        "synthetic-live" => compile_source_fixture(live_builder(), &source),
        _ => panic!("unknown source fixture mode `{mode}`"),
    };
    let parsed = ParsedProgram::from_bytes(&bytecode).expect("generated bytecode must parse");
    let catalog = mech_stdlib::native_plan_catalog();
    let functions = parsed
        .instructions
        .iter()
        .filter_map(BytecodeInstruction::runtime_function)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .map(|id| {
            catalog
                .runtime_entries()
                .find(|entry| entry.id.raw() == id)
                .unwrap_or_else(|| panic!("source fixture emitted unknown runtime ID {id:016x}"))
                .name
                .clone()
        })
        .collect::<Vec<_>>();
    fs::write(output, bytecode).expect("failed to write source fixture bytecode");
    fs::write(
        functions_output,
        serde_json::to_vec(&functions).expect("runtime function names must serialize"),
    )
    .expect("failed to write source fixture runtime names");
}

fn compile_structural_match(source: &str) -> Vec<u8> {
    fn find(node: SyntaxNode) -> Option<ExpressionSyntax> {
        if node.kind() == SyntaxKind::Expression {
            return ExpressionSyntax::cast(node);
        }
        node.children().find_map(find)
    }

    let parsed = parse_canonical_phase_2i_rule_for_test(
        TextSnapshot::new(DocumentId(0x535452554354), Revision(1), source).unwrap(),
        rules::EXPRESSION,
        ParseConfig::default(),
    )
    .expect("structural-match expression must parse");
    assert!(parsed.is_strictly_clean(), "{:?}", parsed.diagnostics);
    assert_eq!(parsed.consumed.end.0 as usize, source.len());
    let artifact = CanonicalSourceFrontend
        .compile_expression(&find(parsed.syntax()).expect("expression syntax"))
        .expect("structural-match semantics")
        .compile_artifact()
        .expect("structural-match artifact");
    encode_program_artifact_bytecode_v1(&artifact).expect("structural-match bytecode")
}

fn compile_standard(source: &str) -> Vec<u8> {
    compile_source_fixture(
        RuntimeBuilder::new().function_catalog(mech_stdlib::source_catalog()),
        source,
    )
}

fn compile_source_fixture(builder: RuntimeBuilder, source: &str) -> Vec<u8> {
    let mut compiler = builder
        .build_compiler()
        .expect("program compiler construction failed");
    compiler
        .compile_source(source)
        .map(|product| product.into_parts().1)
        .expect("source fixture bytecode compilation failed")
}

fn cli_builder() -> RuntimeBuilder {
    RuntimeBuilder::new()
        .function_catalog(mech_stdlib::source_catalog())
        .host_factory(selected_planning_host_factory("cli").unwrap())
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: "cli".to_owned(),
            provider: "cli".to_owned(),
            settings: empty(),
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: "cli/stdout".to_owned(),
            operations: vec!["write".to_owned()],
            paths: vec!["line".to_owned()],
        })
}

fn host_builder(provider: &str) -> RuntimeBuilder {
    let (instance, target, operations, paths, settings) = host_configuration(provider);
    RuntimeBuilder::new()
        .function_catalog(mech_stdlib::source_catalog())
        .host_factory(selected_planning_host_factory(provider).unwrap())
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: instance.to_owned(),
            provider: provider.to_owned(),
            settings,
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: target.to_owned(),
            operations: operations.into_iter().map(str::to_owned).collect(),
            paths: paths.into_iter().map(str::to_owned).collect(),
        })
}

fn host_configuration(
    provider: &str,
) -> (
    &'static str,
    &'static str,
    Vec<&'static str>,
    Vec<&'static str>,
    ConfigValue,
) {
    match provider {
        "console" => (
            "console",
            "console/output",
            vec!["write"],
            vec!["line"],
            empty(),
        ),
        "time" => (
            "clock",
            "clock/clock",
            vec!["read"],
            vec!["second"],
            empty(),
        ),
        "timer" => ("timer", "timer/tick", vec!["read"], vec!["tick"], empty()),
        "scene" => (
            "scene",
            "scene/frame",
            vec!["write"],
            vec!["replace"],
            ConfigValue::Map(BTreeMap::from([
                (
                    "renderer".to_owned(),
                    ConfigValue::String("canvas".to_owned()),
                ),
                (
                    "selector".to_owned(),
                    ConfigValue::String("#scene".to_owned()),
                ),
            ])),
        ),
        "robot-arm" => ("arm", "arm/commands", vec!["move"], vec!["move"], empty()),
        _ => panic!("unsupported host provider `{provider}`"),
    }
}

fn live_builder() -> RuntimeBuilder {
    let (factory, _driver) = TestLiveHostFactory::new().unwrap();
    RuntimeBuilder::new()
        .function_catalog(mech_stdlib::source_catalog())
        .module_manifest(ModuleManifestConfig {
            name: TEST_LIVE_PROVIDER.to_owned(),
            exports: vec![
                ModuleManifestExportConfig {
                    name: TEST_LIVE_CONTEXT.to_owned(),
                    kind: ModuleManifestExportKind::Context,
                    base_uri: TEST_LIVE_BASE_URI.to_owned(),
                    operations: vec!["read".to_owned()],
                },
                ModuleManifestExportConfig {
                    name: TEST_LIVE_OUTPUT_CONTEXT.to_owned(),
                    kind: ModuleManifestExportKind::Context,
                    base_uri: TEST_LIVE_OUTPUT_BASE_URI.to_owned(),
                    operations: vec!["write".to_owned()],
                },
            ],
        })
        .unwrap()
        .host_factory(Box::new(factory))
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: TEST_LIVE_INSTANCE.to_owned(),
            provider: TEST_LIVE_PROVIDER.to_owned(),
            settings: empty_settings(),
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: format!("{TEST_LIVE_INSTANCE}/{TEST_LIVE_CONTEXT}"),
            operations: vec!["read".to_owned()],
            paths: vec![TEST_LIVE_PATH.to_owned()],
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: format!("{TEST_LIVE_INSTANCE}/{TEST_LIVE_OUTPUT_CONTEXT}"),
            operations: vec!["write".to_owned()],
            paths: vec![
                TEST_LIVE_TUPLE_PATH.to_owned(),
                TEST_LIVE_RECORD_PATH.to_owned(),
            ],
        })
}

fn empty() -> ConfigValue {
    ConfigValue::Map(BTreeMap::new())
}
