use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;

use mech_build::selected_planning_host_factory;
use mech_core::{
    BytecodeInstruction, ModuleManifestConfig, ModuleManifestExportConfig,
    ModuleManifestExportKind, ParsedProgram, Ref, Value,
};
use mech_engine::{MechProgram, MechProgramConfig};
use mech_native_live_host_fixture::{
    TEST_LIVE_BASE_URI, TEST_LIVE_CONTEXT, TEST_LIVE_INSTANCE, TEST_LIVE_PATH, TEST_LIVE_PROVIDER,
    TEST_LIVE_OUTPUT_BASE_URI, TEST_LIVE_OUTPUT_CONTEXT, TEST_LIVE_RECORD_PATH,
    TEST_LIVE_TUPLE_PATH, TestLiveHostFactory, empty_settings,
};
use mech_runtime::{
    ConfigValue, HostInstanceConfig, PlannedPureHostFunction, RunResourceGrantConfig,
    RuntimeBuilder, RuntimeValueSnapshot,
};

fn main() {
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    let [output, functions_output, mode, source] = arguments.as_slice() else {
        panic!(
            "usage: bytecode-v1-source-generator <output.mecb> <functions.json> <mode> <source>"
        );
    };
    let bytecode = match mode.as_str() {
        "standard" => compile_standard(&source),
        "cli" => compile_planning(cli_builder(), &source),
        "console" | "time" | "timer" | "scene" | "robot-arm" => {
            compile_planning(host_builder(&mode), &source)
        }
        "actor" => compile_planning(actor_builder(), &source),
        "synthetic-live" => compile_planning(live_builder(), &source),
        _ => panic!("unknown source fixture mode `{mode}`"),
    };
    let parsed = ParsedProgram::from_bytes(&bytecode).expect("generated bytecode must parse");
    let catalog = mech_stdlib::native_plan_catalog();
    let functions = parsed
        .instructions
        .iter()
        .filter_map(BytecodeInstruction::runtime_function)
        .collect::<BTreeSet<_>>()
        .into_iter()
        .map(|id| {
            catalog
                .runtime_entries()
                .find(|entry| entry.id.raw() == id)
                .unwrap_or_else(|| panic!("source fixture emitted unknown runtime ID {id:016x}"))
                .name
                .clone()
        })
        .collect::<Vec<_>>();
    fs::write(output, bytecode).expect("failed to write source fixture bytecode");
    fs::write(
        functions_output,
        serde_json::to_vec(&functions).expect("runtime function names must serialize"),
    )
    .expect("failed to write source fixture runtime names");
}

fn compile_standard(source: &str) -> Vec<u8> {
    let mut program = MechProgram::with_function_catalog(
        MechProgramConfig::default(),
        mech_stdlib::source_catalog(),
    );
    program
        .run_string(source)
        .expect("full source fixture execution failed");
    program
        .compile_bytecode()
        .expect("full source fixture bytecode compilation failed")
}

fn compile_planning(builder: RuntimeBuilder, source: &str) -> Vec<u8> {
    let mut runtime = builder
        .build()
        .expect("planning runtime construction failed");
    runtime
        .run_string(source)
        .expect("planning source fixture execution failed");
    runtime
        .compile_program_bytecode()
        .expect("planning source fixture bytecode compilation failed")
}

fn cli_builder() -> RuntimeBuilder {
    RuntimeBuilder::new()
        .planning()
        .function_catalog(mech_stdlib::source_catalog())
        .host_factory(selected_planning_host_factory("cli").unwrap())
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: "cli".to_owned(),
            provider: "cli".to_owned(),
            settings: empty(),
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: "cli/stdout".to_owned(),
            operations: vec!["write".to_owned()],
            paths: vec!["line".to_owned()],
        })
}

fn host_builder(provider: &str) -> RuntimeBuilder {
    let (instance, target, operations, paths, settings) = host_configuration(provider);
    RuntimeBuilder::new()
        .planning()
        .function_catalog(mech_stdlib::source_catalog())
        .host_factory(selected_planning_host_factory(provider).unwrap())
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: instance.to_owned(),
            provider: provider.to_owned(),
            settings,
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: target.to_owned(),
            operations: operations.into_iter().map(str::to_owned).collect(),
            paths: paths.into_iter().map(str::to_owned).collect(),
        })
}

fn host_configuration(
    provider: &str,
) -> (
    &'static str,
    &'static str,
    Vec<&'static str>,
    Vec<&'static str>,
    ConfigValue,
) {
    match provider {
        "console" => (
            "console",
            "console/output",
            vec!["write"],
            vec!["line"],
            empty(),
        ),
        "time" => (
            "clock",
            "clock/clock",
            vec!["read"],
            vec!["second"],
            empty(),
        ),
        "timer" => ("timer", "timer/tick", vec!["read"], vec!["tick"], empty()),
        "scene" => (
            "scene",
            "scene/frame",
            vec!["write"],
            vec!["replace"],
            ConfigValue::Map(BTreeMap::from([
                (
                    "renderer".to_owned(),
                    ConfigValue::String("canvas".to_owned()),
                ),
                (
                    "selector".to_owned(),
                    ConfigValue::String("#scene".to_owned()),
                ),
            ])),
        ),
        "robot-arm" => ("arm", "arm/commands", vec!["move"], vec!["move"], empty()),
        _ => panic!("unsupported host provider `{provider}`"),
    }
}

fn actor_builder() -> RuntimeBuilder {
    RuntimeBuilder::new()
        .planning()
        .function_catalog(mech_stdlib::source_catalog())
        .host_function(PlannedPureHostFunction::new(
            "actor/state/id",
            |_context, _arguments| {
                RuntimeValueSnapshot::try_capture(&Value::String(Ref::new(String::new())))
            },
            |_context, _arguments| panic!("actor/state/id executed while planning"),
        ))
        .unwrap()
}

fn live_builder() -> RuntimeBuilder {
    let (factory, _driver) = TestLiveHostFactory::new().unwrap();
    RuntimeBuilder::new()
        .planning()
        .function_catalog(mech_stdlib::source_catalog())
        .module_manifest(ModuleManifestConfig {
            name: TEST_LIVE_PROVIDER.to_owned(),
            exports: vec![
                ModuleManifestExportConfig {
                    name: TEST_LIVE_CONTEXT.to_owned(),
                    kind: ModuleManifestExportKind::Context,
                    base_uri: TEST_LIVE_BASE_URI.to_owned(),
                    operations: vec!["read".to_owned()],
                },
                ModuleManifestExportConfig {
                    name: TEST_LIVE_OUTPUT_CONTEXT.to_owned(),
                    kind: ModuleManifestExportKind::Context,
                    base_uri: TEST_LIVE_OUTPUT_BASE_URI.to_owned(),
                    operations: vec!["write".to_owned()],
                },
            ],
        })
        .unwrap()
        .host_factory(Box::new(factory))
        .unwrap()
        .host_instance(HostInstanceConfig {
            name: TEST_LIVE_INSTANCE.to_owned(),
            provider: TEST_LIVE_PROVIDER.to_owned(),
            settings: empty_settings(),
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: format!("{TEST_LIVE_INSTANCE}/{TEST_LIVE_CONTEXT}"),
            operations: vec!["read".to_owned()],
            paths: vec![TEST_LIVE_PATH.to_owned()],
        })
        .run_resource_grant(RunResourceGrantConfig {
            target: format!("{TEST_LIVE_INSTANCE}/{TEST_LIVE_OUTPUT_CONTEXT}"),
            operations: vec!["write".to_owned()],
            paths: vec![
                TEST_LIVE_TUPLE_PATH.to_owned(),
                TEST_LIVE_RECORD_PATH.to_owned(),
            ],
        })
}

fn empty() -> ConfigValue {
    ConfigValue::Map(BTreeMap::new())
}
