[package]
name = "mech-bytecode"
version = "0.3.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech bytecode compiler."
documentation = "https://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/mech"
keywords = ["mech", "language", "programming", "bytecode", "compiler"]
categories = ["compilers"]
license = "Apache-2.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
mech-core = { version = "0.3.5", path = "../core", default-features = false, features = ["compiler"] }

[dev-dependencies]
mech-core = { version = "0.3.5", path = "../core", default-features = false, features = ["program", "f64", "tuple"] }
