[package]
name = "mech-string"
version = "0.3.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Comparison library for the Mech language"
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-machines/string"
keywords = ["mech", "language", "programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2024"

[badges]
gitlab = { repository = "mech-lang/machines/compare", branch = "main" }
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["rlib"]

[features]
no_std = ["mech-core/no_std"]

default = []
runtime = ["mech-core/functions"]
source = ["runtime"]
compiler = ["runtime", "mech-core/compiler"]
native-plan = ["runtime", "mech-core/native-plan"]
native-link = ["runtime"]
standard_values = ["string", "row_vectord", "vectord", "matrixd"]
standard_operations = ["string_default"]
standard_runtime = ["runtime", "standard_values", "standard_operations"]
standard_source = ["standard_runtime", "source"]
standard_compiler = ["standard_source", "compiler"]
full_values = [
  "string", "matrix1", "matrix2", "matrix3", "matrix4", "matrix2x3", "matrix3x2",
  "row_vector2", "row_vector3", "row_vector4",
  "vector2", "vector3", "vector4", "row_vectord", "vectord", "matrixd",
]
full_operations = ["string_default"]
full_runtime = ["runtime", "full_values", "full_operations"]
full_source = ["full_runtime", "source"]
full_compiler = ["full_source", "compiler"]

string_default = ["concat"]
concat = ["runtime", "string"]

string = ["mech-core/string"]

# Matrix
matrix = ["nalgebra", "mech-core/matrix"]
row_vector4 = ["matrix", "mech-core/row_vector4"]
row_vector3 = ["matrix", "mech-core/row_vector3"]
row_vector2 = ["matrix", "mech-core/row_vector2"]
vector4 = ["matrix", "mech-core/vector4"]
vector3 = ["matrix", "mech-core/vector3"]
vector2 = ["matrix", "mech-core/vector2"]
matrix4 = ["matrix", "mech-core/matrix4"]
matrix3 = ["matrix", "mech-core/matrix3"]
matrix2 = ["matrix", "mech-core/matrix2", "mech-core/matrix"]
matrix1 = ["matrix", "mech-core/matrix1"]
matrix2x3 = ["matrix", "mech-core/matrix2x3"]
matrix3x2 = ["matrix", "mech-core/matrix3x2"]
row_vectord =["matrix",  "mech-core/row_vectord"]
vectord = ["matrix",  "mech-core/vectord"]
matrixd = ["matrix",  "mech-core/matrixd"]

[dependencies]
mech-core = { path = "../../src/core", version = "0.3.5", default-features = false }

paste = "1.0.15"
nalgebra = {version="0.34.1", optional = true}

[workspace]
